name: (Windows) Game Packaged Build

on:
  push:
    branches: main
    paths:
      - 'Config/**'
      - 'Content/**'
      - 'Plugins/**'
      - 'Source/**'
      - '*.uproject'

jobs:
  compile:
    uses: BlueprintAttributes/workflows/.github/workflows/game-build.yml@main
    with:
      ue_versions: "['5.3']"
      platform: Windows
      build_configuration: Development
      plugin_repository: BlueprintAttributes/BlueprintAttributes
      plugin_path: Plugins/BlueprintAttributes
    secrets: inherit